void a6bd (void);
void a4bd (void);
void a9bd (void);
void abd (void);
void awd (void);
void s4bd (void);
void s6bd (void);
void s9bd (void);
void sbd (void);
void swd (void);
void cmpc (void);
void scd (void);
void scdr (void);
void scm (void);
void scmr (void);
void tct (void);
void tctr (void);
void mlr (void);
void mrl (void);
void mve (void);
void mvne (void);
void mvt (void);
void mvt (void);
void cmpn (void);
void mvn (void);
void csl (bool isSZTL);
void csr (bool isSZTR);
