void setupEISoperands (void);
void a4bd (void);
void s4bd (void);
void axbd (uint sz);
void sxbd (uint sz);
void cmpc (void);
void scd (void);
void scdr (void);
void scm (void);
void scmr (void);
void tct (void);
void tctr (void);
void mlr (void);
void mrl (void);
void mve (void);
void mvne (void);
void mvt (void);
void cmpn (void);
void mvn (void);
void csl (bool isSZTL);
void csr (bool isSZTR);
void cmpb (void);
void btd (void);
void dtb (void);
void ad2d (void);
void ad3d (void);
void sb2d (void);
void sb3d (void);
void mp2d (void);
void mp3d (void);
void dv2d (void);
void dv3d (void);
