#!/bin/sh
#set -x

Version="1.0.1 (HWR)"
verbose=0
regen=0
while [ $# -ge 1 ]
do
    case $1 in
        -h | --help     ) echo help; exit ;;
        -v | --version  ) echo $Version ; exit ;;
        -V | --Verbose  ) verbose=1 ; echo Verbose mode;;
        -R | --Regenerate) regen=1 ;;
        -r              ) run=$2; shift ;;
        -r*             ) run=${1#-r};;
        -e              ) EPOCH=$2; shift ; echo EPOCH="$EPOCH";;
        -e*             ) EPOCH=${1#-e}; echo EPOCH="$EPOCH";;
#        --epoch=        ) EPOCH=${1#*=}; echo EPOCH="$EPOCH";;
#        -o              ) filename=$2; shift ;;
#        -o*             ) filename=${1#-o} ;;
#        --output=       ) filename=${1#*=} ;;
#        -s              ) searchphrase=$2; shift ;;
#        -s*             ) ${1#-s} ;;
#        --search=       ) searchphrase=${1#*=} ;;
#        -f              ) format=$2; shift ;;
#        -f*             ) format=${1#-f} ;;
#        --format=       ) format${1#*=} ;;
        -*              ) echo invalid option >&2; exit 1 ;;
        *               ) echo invalid option >&2; exit 1 ;;
    esac
    shift
done

oldIFS=$IFS
IFS='
'
set -f
set -- $args
IFS=$oldIFS
set +f


BASE=~/Documents/dps8m\ \(New\)/XCode/DerivedData/Build/Products/Debug

DPS8=${BASE}/dps8
AS8=${BASE}/as8+

SRC="TestAppendA TestCSR TestAppend TestString TestFP TestEIS TestFXE TestAddrMods"


#
# See if user wants to regenate 1 or all of the regression outputs
#
if [ "$regen" -eq 1 ]
then
    read -p "Are you sure you want to regerate regression outputs (y/n)? "
    if [ "$REPLY" == "y" ]
    then
        echo "Will regenerate regression outputs"
        for VARIABLE in $SRC
        do
            TEST="$VARIABLE".out

            echo Regenerating "$TEST" ...
            "$DPS8" "$VARIABLE" > $TEST

        done
        exit
    else
        echo Aborting ...
        exit
    fi
fi

if [ "$verbose" -eq 1 ]
then
    echo Base directory = "$BASE"
    echo as8 = "$AS8"
    echo dps8 = "$DPS8"
    echo Regenerate = "$regen"
fi

if [ $run ]
then
    echo Will run "$run"
fi



#EPOCH=$(date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s")
EPOCH=$(date +%s)

echo Epoch is $EPOCH

for VARIABLE in $SRC
do
	echo  Running "$VARIABLE" ...

	TEST="$VARIABLE"."$EPOCH"

#    $AS8 -Isrc src/"$VARIABLE".as8 -o"$VARIABLE".o8
	"$DPS8" "$VARIABLE" > $TEST
	diff -w $TEST "$VARIABLE".out
	rm $TEST
done
