#!/bin/sh
#set -x

BASE=~/Documents/dps8m\ \(New\)/XCode/DerivedData/Build/Products/Debug

DPS8=${BASE}/dps8
AS8=${BASE}/as8+

#echo Base directory = "$BASE"
#echo as8 = "$AS8"
#echo dps8 = "$DPS8"

SRC="TestAppendA TestCSR TestAppend TestString TestFP TestEIS TestFXE"

EPOCH=$(date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s")

echo Epoch is $EPOCH

for VARIABLE in $SRC
do
echo  Running "$VARIABLE" ...

TEST="$VARIABLE"."$EPOCH"

#    $AS8 -Isrc src/"$VARIABLE".as8 -o"$VARIABLE".o8
"$DPS8" "$VARIABLE" > $TEST
diff $TEST "$VARIABLE".out
rm $TEST
done
