all : ImplementationNotes.pdf

ImplementationNotes.pdf : ImplementationNotes.tex
	latex ImplementationNotes.tex
	dvipdf ImplementationNotes.dvi

clean :
	-rm ImplementationNotes.dvi ImplementationNotes.pdf ImplementationNotes.aux ImplementationNotes.log 
